# Install the apt prerequisites
language: python

env:
  global:
    - PRODUCTION=true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https curl

# Clean and don't fail
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.57.2_Linux-64bit.deb
  - hugo version
  - rm -rf public 2> /dev/null

# Build the website
script:
  - hugo
  - hugo -s blog/ -d $(pwd)/public/blog
  - hugo -s bazar/ -d $(pwd)/public/bazar

# Deploy to GitHub pages
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  github_token: $GITHUB_TOKEN
  fqdn: $GTIHUB_DOMAIN
  skip_cleanup: true
  verbose: true
  keep-history: true
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master
