# Page settings
baseurl = "https://ffrizzo.com/"
languageCode = "en-us"
title = "Fabiano Frizzo"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-63537429-1"
disableKinds = ["404", "RSS", "Sitemap"]

[params]
    # Profile section
    [params.profile]
        enable = true
        name = "Fabiano Frizzo"
        tagline = "Software Engineer/Cloud Engineer"

    # Contact section
    [params.contact]
        enable = true
        location = "Cascavel, PR, Brazil"
        [[params.contact.list]]
        class = "email"
        icon = "fas fa-envelope"
        url = "mailto: ffrizzo@gmail.com"
        text = "ffrizzo@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fas fa-phone"
        url = "tel:+5545999697850"
        text = "+55 45 999697850"

        [[params.contact.list]]
        class = "website"
        icon = "fas fa-globe"
        url = "https://ffrizzo.com/blog"
        text = "ffrizzo.com/blog"

    [params.social]
        enable = true
        [[params.social.list]]
        class = "linkedin"
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ffrizzo"

        [[params.social.list]]
        class = "stack-overflow"
        icon = "fab fa-stack-overflow"
        url = "https://stackoverflow.com/users/1550221/fabiano-frizzo"

        [[params.social.list]]
        class = "github"
        icon = "fab fa-github"
        url = "https://github.com/ffrizzo"

        [[params.social.list]]
        class = "twitter"
        icon = "fab fa-twitter"
        url = "https://twitter.com/ffrizzo"

   [params.skills]
        enable = true
        [[params.skills.list]]
        title = "Programming Languages"
        [[params.skills.list.items]]
        details = "Go, Rust, Java, Python, NodeJS"
        [[params.skills.list]]
        title = "Cloud/DevOps Tools"
        [[params.skills.list.items]]
        details = "Docker, Kubernetes, Nomad, Spinnaker, Terraform, Packer, Ansible"
        [[params.skills.list]]
        title = "Cloud Providers"
        [[params.skills.list.items]]
        details = "AWS, GCP, Azure"

    # Education section
    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Master Degree"
        university = "Univel University - Cascavel, Brazil"
        dates = "2005 - 2008"

    # Languages section
    [params.languages]
        enable = true
        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Blockchain, Home Automation, Raspberry PI"
        [[params.interests.list]]
        name = "Arduino, Car Hacking, Car Tuning"

    # Summary section
    [params.summary]
        enable = true
        text = "A Senior Software engineer with 13+ years of experience delivering high-quality software, specialized in Cloud/DevOps and Backend development."

    # Experiences section
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Cloud Engineer - Contractor"
        dates = "01/2023 - present"
        company = "Fanatics Inc(remote)"
        details = "As a member of the CI/CD Team, work on the development of internal tools to improve user experience on deployments to multiple cloud providers using Spinnaker to deploy to AWS and Kubernetes also bringing Nomad from Hashicorp as a new cloud provider"

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "03/2022 - 09/2022"
        company = "WalletConnect Inc(remote)"
        details = "Worked as a Go engineer on projects that support authentication with Supabase and integration with Waku. Also worked on the first implementation of the V2 protocol in Rust. Got involved with infrastructure and CI/CD improvements."

        [[params.experience.list]]
        title = "Cloud Engineer - Contractor"
        dates = "01/2019 - 03/2022"
        company = "Fanatics Inc(remote)"
        details = "Built tools to help internal teams deploy applications to AWS(EC2) and Kubernetes, reducing the risks and improving the deployment process, also helping set up new applications. Also, as part of the CI/CD team, we manage Spinnaker, Kubernetes(kops), GitlabCI, Github, and Artifactory."

        [[params.experience.list]]
        title = "Senior Software/DevOps Engineer"
        dates = "11/2016 - 12/2018"
        company = "FoodLogiQ(remote)"
        details = "Worked with high-priority tickets to fix issues that affected customers and required quick fixes. I moved to work more focused on DevOps to help improve infrastructure reliability and security, reducing costs with the cloud provider. Have introduced new tools(Terraform, Ansible, Packer) to manage the cloud, improved how containers are built and deployed, built tools to facilitate the integration of other teams with the cloud, and enhanced repetitive daily tasks. Applications building with Go and AngularJS."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "03/2016 - 10/2016"
        company = "Enlight Research(remote)"
        details = "Built new features and improved the application performance, stability, and code quality built integrations with external APIs. The core applications used Go and AngularJS on the backend and the frontend, respectively. Worked in the DevOps area to improve how we built the container images and introduced a proper CI/CD environment, reducing the friction on releases and making it more reliable."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "02/2010 - 03/2016"
        company = "Integritas Solutions, Inc(remote)"
        details = "Build new applications and work on maintenance using various technologies such as Java, NodeJs, Adobe Flex, AngularJS, and EmberJS. As a DevOps engineer helped set up applications to run CI/CD(Jenkins) and built servers with Apache, Nginx, Jboss, MySQL, and PostgreSQL. I worked with Vagrant to deliver a better experience for devs to start on projects. I Worked on multiple applications for different customers."

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "07/2009 - 05/2015"
        company = "Escritório Contábil Iguaçu(remote)"
        details = "Built a new ERP on a small team using Java, Adobe Flex, and PostgreSQL. Built integrations with government applications. As SysAdmin configured the on-premise servers to run Apache, JBoss, and PostgreSQL."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "02/2011 - 09/2011"
        company = "SetPoint(remote)"
        details = "Worked on adding new features and bug fixes on an OpenSource ERP Project called FreedomERP. FreedomERP was a project built with Java Swing using the Firebird database."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "01/2010 - 11/2010"
        company = "NetSar(remote)"
        details = "As a team member that works mainly with the ERP Application. The ERP was built using Java and Adobe Flex. Implemented integrations with third-party applications and APIs."

        [[params.experience.list]]
        title = "Junior Software Developer"
        dates = "08/2006 - 05/2007"
        company = "Sicoob Cascavel"
        details = "Built internal tools with Delphi and Firebird to help Account Managers calculate the risk for money loans and provide metrics to enable customers to make the best investment."

    [params.footer]
        copyright = "Fabiano Frizzo"
