# Page settings
baseurl = "https://ffrizzo.com/"
languageCode = "en-us"
title = "Fabiano Frizzo"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-63537429-1"
disableKinds = ["404", "RSS", "Sitemap"]

[params]
    # Profile section
    [params.profile]
        enable = true
        name = "Fabiano Frizzo"
        tagline = "Cloud Engineer/DevOps Engineer"

    # Contact section
    [params.contact]
        enable = true
        location = "Cascavel, PR, Brazil"
        [[params.contact.list]]
        class = "email"
        icon = "fas fa-envelope"
        url = "mailto: ffrizzo@gmail.com"
        text = "ffrizzo@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fas fa-phone"
        url = "tel:+5545999697850"
        text = "+55 45 999697850"

        [[params.contact.list]]
        class = "website"
        icon = "fas fa-globe"
        url = "https://ffrizzo.com/blog"
        text = "ffrizzo.com/blog"

    [params.social]
        enable = true
        [[params.social.list]]
        class = "linkedin"
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ffrizzo"

        [[params.social.list]]
        class = "stack-overflow"
        icon = "fab fa-stack-overflow"
        url = "https://stackoverflow.com/users/1550221/fabiano-frizzo"
        
        [[params.social.list]]
        class = "github"
        icon = "fab fa-github"
        url = "https://github.com/ffrizzo"

        [[params.social.list]]
        class = "twitter"
        icon = "fab fa-twitter"
        url = "https://twitter.com/ffrizzo"

    # Education section
    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Bachelor’s Degree"
        university = "Univel University - Cascavel, Brazil"
        dates = "2005 - 2008"

   [params.skills]
        enable = true
        [[params.skills.list]]
        title = "Cloud/DevOps Tools"
        [[params.skills.list.items]]
        details = "Kubernetes, Spinnaker, Terraform, Packer, Ansible"
        [[params.skills.list]]
        title = "Cloud Providers"
        [[params.skills.list.items]]
        details = "AWS, GCP"
        [[params.skills.list]]
        title = "Programming Languages"
        [[params.skills.list.items]]
        details = "Go, Java, Python, NodeJS"

    # Languages section
    [params.languages]
        enable = true
        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Home Automation, "
        [[params.interests.list]]
        name = "Arduino, Raspberry PI"
        [[params.interests.list]]
        name = "Bike, Music"

    # Summary section
    [params.summary]
        enable = true
        text = "10+ years of experience working remotely with minimum supervision on different industries and delivering high-quality software using the best practices with different programming languages, on last 5+ years with focus on DevOps/Cloud Engineering implementing tools to improve utilization of cloud provider and reducing costs, also had build tools for teams to improve how they iterate with the cloud providers and improve performance on daily tasks"

    # Experiences section
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Cloud Engineer"
        dates = "01/2019 - Present"
        company = "Augmen Group(remote)"
        details = "As a member of CI/CD Team that manages tools like GitlabCI, Github, Artifactory. Built a tool to integrate with Spinnaker to improve how teams delivery applications to AWS and to help on migration to Kubernetes"

        [[params.experience.list]]
        title = "Senior Software/DevOps Engineer"
        dates = "11/2016 - 12/2018"
        company = "FoodLogiQ(remote)"
        details = "Worked with high priority tickets to fix issues that affected customers and required quick fixes. I moved to work more focused on DevOps to help improving infrastructure reliability and security, also reducing costs with the cloud provider. Have introduced new tools(Terraform, Ansible, Packer) to manage the cloud, improved how containers are build and deployed, built tools to facilitate the integration of other teams with cloud, and improved repetitive daily tasks. Applications were built with Go and AngularJS"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "03/2016 - 10/2016"
        company = "Enlight Research(remote)"
        details = "Built new features and made improvements in different areas of application, built integrations with external APIs. All applications were built with Go and AngularJS"

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "02/2010 - 03/2016"
        company = "Integritas Solutions, Inc(remote)"
        details = "Worked on multiple applications for different customers. Built new applications and work on maintenance using different technologies such as Java, NodeJs, Adobe Flex, AngularJS, EmberJS. As DevOps configured applications tools to run CI/CD(Jenkins, Apache, Nginx) and help other devs on setup the environment using Vagrant and Docker"

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "07/2009 - 05/2015"
        company = "Escritório Contábil Iguaçu(remote)"
        details = "Built a new ERP on a small team using Java, Adobe Flex, PostgreSQL, built integrations with government applications. As SysAdmin configured the on-premise servers to run Apache, JBoss, PostgreSQL"
        
        [[params.experience.list]]
        title = "Software Developer"
        dates = "02/2011 - 09/2011"
        company = "SetPoint(remote)"
        details = "Worked to adding new features and on bugs fixes on FreedomERP an OpenSource ERP Project. FreedomERP is a project built with Java Swing application."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "01/2010 - 11/2010"
        company = "NetSar(remote)"
        details = "As a member of a team that works mainly with the ERP Application. The ERP was built using Java and Adobe Flex, implemented few integrations with third-party applications and APIs"

        [[params.experience.list]]
        title = "Junior Software Developer"
        dates = "08/2006 - 05/2007"
        company = "Sicoob Cascavel"
        details = "Built internal tools with Delphi and Firebird to help Account Managers calculate the risk for money loan and providing metrics to help customers to do the best investment"
    
    [params.footer]
        copyright = "Fabiano Frizzo"
