baseurl = "http://blog.ffrizzo.com"
MetaDataFormat = "toml"
theme="hugo-redlounge"
languageCode = "en-us"
title = "Fabiano Frizzo"


author = "Fabiano Frizzo ffrizzo@gmail.com"
Keywords = "desenvolvimento"
disqusShortname = "ffrizzo"

[params]
  sidebartitle = "Fabiano Frizzo"
  sidebartagline = ""
  gaid = "UA-63537429-1"
  socialsharing = true
  highlightStyle = "tomorrow-night"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/posts"

# [[menu.main]]
#   name = "Sobre"
#   url = "/about"

[[menu.footer]]
  name = "Blog"
  url = "/posts"

# [[menu.footer]]
#   name = "Sobre"
#   url = "/about"

[[menu.social]]
  pre = "<i class='fa fa-github'></i>"
  url = "http://github.com/ffrizzo"
  identifier = "github"

[[menu.social]]
  pre = "<i class='fa fa-linkedin'></i>"
  url = "http://linkedin.com/in/ffrizzo"
  identifier = "linkedin"

[[menu.social]]
  pre = "<i class='fa fa-google-plus'></i>"
  url = "https://plus.google.com/u/0/+FabianoFrizzo/"
  identifier = "gplus"

[[menu.social]]
  pre = "<i class='fa fa-twitter'></i>"
  url = "http://www.twitter.com/ffrizzo"
  identifier = "twitter"

[[menu.social]]
  pre = "<i class='fa fa-facebook'></i>"
  url = "http://facebook.com/fabiano.frizzo"
  identifier = "facebook"
