# Page settings

baseurl = "https://ffrizzo.com/"
languageCode = "en-us"
title = "Fabiano Frizzo"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-63537429-1"

disableKinds = ["404", "RSS", "Sitemap"]

[params]
# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"
    styles = "styles-2.css"

    # Profile section
    [params.profile]
        enable = true
        name = "Fabiano Frizzo"
        tagline = "Cloud Engineer, DevOps Engineer, Senior Software Engineer"

    # Contact section
    [params.contact]
        enable = true
        location = "Cascavel, PR, Brazil"

        [[params.contact.list]]
        class = "email"
        icon = "fas fa-envelope"
        url = "mailto: ffrizzo@gmail.com"
        text = "ffrizzo@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fas fa-phone"
        url = "tel:+5545999697850"
        text = "+55 45 999697850"

        [[params.contact.list]]
        class = "website"
        icon = "fas fa-globe"
        url = "//ffrizzo.com/blog"
        text = "ffrizzo.com/blog"

    [params.social]
        enable = true

        [[params.social.list]]
        class = "stack-overflow"
        icon = "fab fa-stack-overflow"
        url = "//stackoverflow.com/users/1550221/fabiano-frizzo"
        text = "fabiano-ffrizzo"
        
        [[params.social.list]]
        class = "github"
        icon = "fab fa-github"
        url = "//github.com/ffrizzo"
        text = "github.com/ffrizzo"        

        [[params.social.list]]
        class = "linkedin"
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/ffrizzo"
        text = "linkedin.com/in/ffrizzo"

        [[params.social.list]]
        class = "twitter"
        icon = "fab fa-twitter"
        url = "//twitter.com/ffrizzo"
        text = "@ffrizzo"

    # Education section
    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Bachelor’s Degree"
        university = "Univel University - Cascavel, Brazil"
        dates = "2005 - 2008"

   [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Go/Java/Python/NodeJS"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "AWS/GCP"
        [[params.skills.list.items]]
        details = "Docker/K8s/Spinnaker"
        [[params.skills.list.items]]
        details = "Terraform/Packer/Ansible"

    # Languages section
    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Bike"
        [[params.interests.list]]
        name = "Music"

    # Summary section
    [params.summary]
        enable = true
        text = "Have more than 11 years of experience on software development. Had the opportunity to work with various technologies such as Go, Java, Python, NodeJS, AngularJS, ReactJS and EmberJS, also have more than 6 years of experience with infrastructure on AWS, more than 4 years working with DevOps culture using Terraform, Ansible, Packer, Docker, Spinnaker, K8s and other tools with focus on AWS and with experience on GCP"

    # Experiences section
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Cloud Engineer"
        dates = "01/2019 - Present"
        company = "Augmen Group"
        details = "Cloud consultant with focus on AWS tools. Currently working as a member of CI/CD Team to provide tools to improve how internal teams delivery they products"

        [[params.experience.list]]
        title = "Senior DevOps Engineer"
        dates = "03/2017 - 12/2018"
        company = "FoodLogiQ"
        details = "As a DevOps engineer improved the infrastructure reliability and security, Introduce tools(terraform, ansible) to configure and manage the infrastructure. Built new tools to help dev teams on daily basis tasks"

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "11/2016 - 03/2017"
        company = "FoodLogiQ"
        details = "As a senior software engineer worked on the high priority tickets to improve and fixes issues that affect customers directly and need quickly resolution using Go"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "03/2016 - 10/2016"
        company = "Enlight Research"
        details = "As a software engineer I've worked to add new functionalities and improve system. Mainly worked with Go and AngularJS also I have configured travis to build and test"

        [[params.experience.list]]
        title = "Senior Full Stack Developer"
        dates = "02/2010 - 03/2016"
        company = "Integritas Solitions, Inc"
        details = "As senior full-stack developer, added and maintained features on the applications for our customers. Developed multiple features on the back-end with Java and on front-end with Adobe Flex/JS(AngularJS, EmberJS), NodeJS in different's projects. As DevOps configuring servers with Jenkins, Tomcat, Apache, Nginx using Vagrant, Docker. Worked remotely"

        [[params.experience.list]]
        title = "Senior Full Stack Developer"
        dates = "07/2009 - 05/2015"
        company = "Escritório Contábil Iguaçu"
        details = "As a senior full-stack developer, added and maintained features on the our application. Developed multiple features on the back-end and front-end with Java and Adobe Flex. As DevOps configuring servers with JBoss As 7, Apache, PostgreSQL"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "02/2011 - 09/2011"
        company = "SetPoint"
        details = "As a senior developer added and maintained features on a open source project Freedom ERP. Developed multiple features on the project using Java and Swing. Worked remotely"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "01/2010 - 11/2010"
        company = "NetSar"
        details = "Worked on maintenance of rich internet application with Java, Adobe Flex and GraniteDS. Integration with third-party apps with company’s applications"

        [[params.experience.list]]
        title = "Software Developer"
        dates = "08/2006 - 05/2007"
        company = "Sicoob Cascavel"
        details = "As a trainee back-end developer, develop internal applications with Delphi and Firebird to help users to calculate a risk of our customers and showing metrics and parameters to help our customers of the best option to invest your money"

    [params.footer]
        copyright = "Fabiano Frizzo"
