# Page settings
baseurl = "https://ffrizzo.com/"
languageCode = "en-us"
title = "Fabiano Frizzo"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-63537429-1"
disableKinds = ["404", "RSS", "Sitemap"]

[params]
    # Profile section
    [params.profile]
        enable = true
        name = "Fabiano Frizzo"
        tagline = "Software Engineer/Cloud Engineer"

    # Contact section
    [params.contact]
        enable = true
        location = "Cascavel, PR, Brazil"
        [[params.contact.list]]
        class = "email"
        icon = "fas fa-envelope"
        url = "mailto: ffrizzo@gmail.com"
        text = "ffrizzo@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fas fa-phone"
        url = "tel:+5545999697850"
        text = "+55 45 999697850"

        [[params.contact.list]]
        class = "website"
        icon = "fas fa-globe"
        url = "https://ffrizzo.com/blog"
        text = "ffrizzo.com/blog"

    [params.social]
        enable = true
        [[params.social.list]]
        class = "linkedin"
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ffrizzo"

        [[params.social.list]]
        class = "stack-overflow"
        icon = "fab fa-stack-overflow"
        url = "https://stackoverflow.com/users/1550221/fabiano-frizzo"

        [[params.social.list]]
        class = "github"
        icon = "fab fa-github"
        url = "https://github.com/ffrizzo"

        [[params.social.list]]
        class = "twitter"
        icon = "fab fa-twitter"
        url = "https://twitter.com/ffrizzo"

   [params.skills]
        enable = true
        [[params.skills.list]]
        title = "Programming Languages"
        [[params.skills.list.items]]
        details = "Go, Rust, Java, Python, NodeJS"
        [[params.skills.list]]
        title = "Cloud/DevOps Tools"
        [[params.skills.list.items]]
        details = "Docker, Kubernetes, Nomad, Spinnaker, Terraform, Packer, Ansibl, Helm"
        [[params.skills.list]]
        title = "Cloud Providers"
        [[params.skills.list.items]]
        details = "AWS, GCP, Azure"
        [[params.skills.list]]
        title = "Other Tools"
        [[params.skills.list.items]]
        details = "Gitlab Pipelines, Github Actions, JFrog Artifactory"

    # Education section
    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Master Degree"
        university = "Univel University - Cascavel, Brazil"
        dates = "2005 - 2008"

    # Languages section
    [params.languages]
        enable = true
        [[params.languages.list]]
        name = "Portuguese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Blockchain, Home Automation, Raspberry PI"
        [[params.interests.list]]
        name = "Arduino, Car Hacking, Car Tuning"

    # Summary section
    [params.summary]
        enable = true
        text = "With over 14 years of specialized experience in software development, my expertise lies in architecting resilient systems and optimizing CI/CD pipelines for enhanced efficiency and scalability. Proficient in AWS, Kubernetes, and key DevOps tools such as Spinnaker and Terraform, I have a proven track record of delivering innovative solutions that significantly improve performance and reduce costs. My extensive experience underscores a consistent dedication to advancing software architecture and driving impactful outcomes. Moreover, I possess strong collaboration skills, enabling me to effectively work with distributed teams across diverse industries."

    # Experiences section
    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Cloud Engineer - Contractor"
        dates = "01/2023 - present"
        company = "Fanatics Inc(remote)"
        details = "As a valued member of the CI/CD Team, I contributed to the development of internal tools focused on enhancing user experience during deployments across multiple cloud providers. Working alongside talented colleagues, we utilized Spinnaker to facilitate deployments to AWS and Kubernetes environments. Additionally, I had the opportunity to introduce Nomad from HashiCorp as a new cloud provider, expanding our deployment options and contributing to the team's evolving capabilities."

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "03/2022 - 09/2022"
        company = "WalletConnect Inc(remote)"
        details = "As a Go engineer, I contributed to projects focused on enhancing authentication with Supabase and integrating with Waku, enriching user experiences and functionality. Additionally, I had the opportunity to participate in pioneering the first implementation of the V2 protocol in Rust, furthering our team's technological advancements. Beyond my primary role, I actively engaged in infrastructure and CI/CD enhancements, recognizing the importance of robust and efficient development processes."

        [[params.experience.list]]
        title = "Cloud Engineer - Contractor"
        dates = "01/2019 - 03/2022"
        company = "Fanatics Inc(remote)"
        details = "As a member of the CI/CD team, I contributed to the development of an in-house deployment tool designed to streamline the deployment process across cloud providers such as AWS and Kubernetes. Leveraging Golang, we built a comprehensive solution comprising a server, CLI, and Terraform provider, aimed at enhancing efficiency and reliability. Additionally, our responsibilities extended to the management of key technologies including Spinnaker, Kubernetes, GitLab CI, GitHub, and Artifactory, ensuring seamless integration and operation within our development ecosystem."

        [[params.experience.list]]
        title = "Senior Software/DevOps Engineer"
        dates = "11/2016 - 12/2018"
        company = "FoodLogiQ(remote)"
        details = "I initially tackled critical customer issues, swiftly resolving high-priority tickets to maintain seamless service delivery. Transitioning towards a more focused DevOps role, I dedicated myself to enhancing infrastructure reliability and bolstering security measures while strategically optimizing costs with our cloud provider. My initiatives included the introduction of pivotal tools like Terraform, Ansible, and Packer, revolutionizing our cloud management practices. I also revamped containerization processes and spearheaded the development of tools facilitating seamless integration with other teams' workflows. Concurrently, I actively contributed to application development, leveraging Go and AngularJS to deliver robust and user-centric solutions."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "03/2016 - 10/2016"
        company = "Enlight Research(remote)"
        details = "I had the opportunity to contribute to our applications by adding new features and refining performance while prioritizing stability and code quality. Additionally, I worked on integrating external APIs to enhance functionality. My primary focus was on backend development using Go and frontend with AngularJS. In the DevOps sphere, I played a part in refining our container image building processes and establishing a more reliable CI/CD environment. These efforts aimed to minimize release friction and improve deployment consistency."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "02/2010 - 03/2016"
        company = "Integritas Solutions, Inc(remote)"
        details = "I've had the opportunity to develop new applications and maintain existing ones using a variety of technologies, including Java, Node.js, Adobe Flex, AngularJS, and Ember.js. As a DevOps engineer, I played a role in establishing CI/CD pipelines (using Jenkins) and configuring servers with Apache, Nginx, JBoss, MySQL, and PostgreSQL. Additionally, I implemented Vagrant to enhance the developer experience, simplifying project setup. Over time, I've worked on multiple applications for diverse clients, gaining valuable experience in meeting different requirements and delivering effective solutions."

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "07/2009 - 05/2015"
        company = "Escritório Contábil Iguaçu(remote)"
        details = "Contributed to the development of a new ERP system using Java and Adobe Flex, collaborating closely with a small team. Integrated the ERP system with government applications to ensure seamless data exchange. Additionally, as a SysAdmin, took charge of configuring on-premise servers, optimizing them for performance and reliability with Apache, JBoss, and PostgreSQL."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "02/2011 - 09/2011"
        company = "SetPoint(remote)"
        details = "Contributed to feature enhancements and bug fixes for FreedomERP, an open-source ERP project. Utilized Java Swing and Firebird database to develop and maintain the system's functionality and user interface."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "01/2010 - 11/2010"
        company = "NetSar(remote)"
        details = "As a team member dedicated to the ERP application, I specialized in Java and Adobe Flex development. I actively integrated third-party applications and APIs, enhancing the ERP's functionality and interoperability."

        [[params.experience.list]]
        title = "Junior Software Developer"
        dates = "08/2006 - 05/2007"
        company = "Sicoob Cascavel"
        details = "Developed internal tools using Delphi and Firebird to support Account Managers in risk assessment for money loans. These tools also provided essential metrics to assist customers in making informed investment decisions."

    [params.footer]
        copyright = "Fabiano Frizzo"
