baseurl = "https://ffrizzo.com/blog"
languageCode = "en-us"
title = "Fabiano Frizzo blog"
author = "Fabiano Frizzo"
theme = "minimal"

disableKinds = ["RSS"]

disqusShortname = "ffrizzo" # delete this to disable disqus comments
googleAnalytics = "UA-63537429-1"

[params]
    author = "Fabiano Frizzo"
    githubUsername = "ffrizzo"
    accent = "#4CAC9D"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "java"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 2

[[menu.icon]]
    url = "mailto:ffrizzo@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ffrizzo/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/ffrizzo/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ffrizzo/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/1550221/fabiano-frizzo/"
    name = "stack-overflow"
    weight = 5
