baseurl = "http://blog.ffrizzo.com"
languageCode = "en-us"
title = "Fabiano Frizzo blog"
author = "Fabiano Frizzo"
theme = "blackburn"

disqusShortname = "ffrizzo"
canonifyurls = true
pagiante = 10

[params]
  brand = ""
  googleAnalytics = "UA-63537429-1"
  disqus = "ffrizzo"
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"

[social]
  twitter = "ffrizzo"
  facebook = "fabiano.frizzo"
  linkedin = "ffrizzo"
  github = "ffrizzo"
  stackoverflow = "1550221/fabiano-frizzo"
